/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cloud_logic_custom": [
        {
            "name": "event",
            "endpoint": "https://ciu1t34mve.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-2:37c75b68-9f7e-4de0-9463-0239fa3abdda",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_6fPVyLIVS",
    "aws_user_pools_web_client_id": "317tkrlq3ffhdmp3o0i4ritagv",
    "oauth": {}
};


export default awsmobile;
